### ISSUE TITLE
[UI] Validate behaviour for non-admins

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#105]
- Permission handling is coming in post 1.0 (#104)
- Need to ensure when the user does hit this.... the UI handles it correctly (doesn't log user out, shows friendly error, etc)

**Comment by richard-cox** [comment]
- https://docs.epinio.io/next/references/authorization#add-a-new-user
  ```
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Secret
  type: BasicAuth
  metadata:
    labels:
      epinio.io/api-user-credentials: "true"
      epinio.io/role: "user"
    name: my-epinio-user
    namespace: epinio
  stringData:
    username: myuser
    password: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
    namespaces: |
      workspace
      workspace2
  EOF
  ```
  - To get password - https://bcrypt-generator.com/ (rounds 10)
