### ISSUE TITLE
[UI] Non admin users prevented from seeing apps after user updates

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A non admin user that deploys an app and later updates the user credentials (not the username itself) will be prevented from seeing the deployed apps. This does not happen for admin users.

Example:
![image (1)](https://user-images.githubusercontent.com/37271841/191700540-f3032e17-61e1-44d0-b426-19008dce8dad.png)

### Expected Behavior

Normal user should be able to see his/her applications after upgrading credentials the same as admins

### Steps To Reproduce

1. Install Epinio and latest UI
2. Log in as `admin` (admin user)
3. Deploy an app, for instance file app with this file: [sample-app.tar.gz](https://github.com/epinio/ui/files/9623983/sample-app.tar.gz) and wait until is done
4. Log out and log in with `epinio` user (regular user)
5. Deploy same app as in step 3
6. Log out
7. Update the users adding more users and rewriting the first ones. I used this `values.yaml` configuration:
```
api:
  # Default users
  users:
    - username: admin
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
    - username: epinio
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
      #user1 password: Hell@World
    - username: user1 
      passwordBcrypt: "$2y$10$xrZYXonrAnklLCURDX2zu.HacO02Fflp5toM/riJ028aNS2PJRutS"
      role: user
      #user2 password: Hell#@~%/=World
    - username: user2 
      passwordBcrypt: "$2y$10$I3/6py4jE4.P5IO1lWKg5e7D3.WQ8JKPX0kHTgPQPjW/h59utwzo6"
      role: user
      #user@test password: Hell@World
    - username: user@test 
      passwordBcrypt: "$2y$10$xrZYXonrAnklLCURDX2zu.HacO02Fflp5toM/riJ028aNS2PJRutS"
      role: admin
      workspaces:
        - workspace
```
8. Apply changes from cli. 
```
helm upgrade --install epinio -n epinio --create-namespace epinio/epinio --set global.domain=172.19.0.3.omg.howdoi.website --set global.tlsIssuer=letsencrypt-epinio  --values /home/mmartin/values.yaml

```
9. Log in again using `admin` (admin user) and `epinio` (regular user) usernames and observe how the apps created by the `epinio` user are not displayed
![image](https://user-images.githubusercontent.com/37271841/191702468-6569a4c6-d72c-4604-b08d-68848470e0d2.png)

### Environment

```markdown
- OS:Linx
- Architecture:amd64
- Epinio Version: v1.2.0-23-g11a2d241
- Cluster:
  - Provider:k3d
  - Options:
  - Kubernetes Version:Version:v1.20.11+k3s2
```
