### ISSUE TITLE
[UI] Implement `app export` feature in UI

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#170]
- https://github.com/epinio/epinio/issues/1352
- To flesh out
- Probably this should be an action for an app (consider also bulk action)

**Comment by mmartin24** [comment]
Checked in branch `ui/export-app-parts` and functionality seems to work:

- Checked UI have new `export` button on successful pushes.

![image](https://user-images.githubusercontent.com/37271841/223121145-328e9c20-4ba8-49de-a600-e8456bfffff4.png)

![image](https://user-images.githubusercontent.com/37271841/223121283-74dc0457-c6ef-4e23-b767-c1e3b8cbeab2.png)

- Checked `Export Manifest` tab exist and works.
- Download files size an types are equal as in CLI. Attached screenshot with comparison directories `cli_export` vs `ui_export`. The only difference I see is is the absence of `app-` prefix. I am no sure if this is intended or not. Aside from that size of files are equal (also content of `values.yaml`)

![image](https://user-images.githubusercontent.com/37271841/223120893-6ece9d9b-357f-4db6-97bf-7a9563836772.png)

So the functionality seems to work in branch. @scures my only questions are:

- Downloaded elements from UI are named `chart.gz` and `image.gz` vs `app-chart.gz` and `app-image.gz` from cli. Is this expected
- User cannot choose path to download into. Is this expected?

**Comment by mmartin24** [comment]
Thanks @scures for the heads up. It was moved into Epinio review so I took a look. I will move back this item into Epinio icebox until then.

**Comment by mmartin24** [comment]
Tested in `epinio-dev`.

New menu `app-export` present with tabs `Manifest` and `Chart and Images`
![image](https://user-images.githubusercontent.com/37271841/231187813-356186c6-0963-4d77-9dc6-79af6d51244c.png)
![image](https://user-images.githubusercontent.com/37271841/231187878-9510679c-0540-4582-afdf-96dd3b4dfa8e.png)

Manifest part already checked and adapted to this new UI here: https://github.com/epinio/epinio-end-to-end-tests/issues/313

## Export part check:

The number of flies and sizes are equal to the one in cli. The only difference is the suffix name `app` in CLI (`app-chart.tar.gz`, `app-image.tar`) and not in UI (`chart.tar.gz`. `image.tar`). Not an issue IMO.

Comparison:

### Exported docs from UI:
```
➜  testapp-helm-chart ll
total 928M
-rw-rw-r-- 1 mmartin mmartin 3,5K abr 11 11:54 chart.tar.gz
-rw-rw-r-- 1 mmartin mmartin 928M abr 11 11:54 image.tar
-rw-rw-r-- 1 mmartin mmartin  383 abr 11 11:54 values.yml
```
Content of `values.yaml`
```
➜  testapp-helm-chart cat values.yml       
epinio:
  appName: testapp
  configpaths: []
  configurations: []
  env: []
  imageURL: 127.0.0.1:30500/apps/workspace-testapp:33b9adf5282b4d56
  ingress: null
  replicaCount: 1
  routes:
  - domain: testapp.192.168.16.3.omg.howdoi.website
    id: testapp.192.168.16.3.omg.howdoi.website
    path: /
  stageID: 33b9adf5282b4d56
  start: null
  tlsIssuer: epinio-ca
  username: admin
```

### Exported docs from CLI:
```
➜  testapp-cli ll
total 928M
-rw-rw-r-- 1 mmartin mmartin 3,5K abr 11 14:01 app-chart.tar.gz
-rw-rw-r-- 1 mmartin mmartin 928M abr 11 14:01 app-image.tar
-rw-rw-r-- 1 mmartin mmartin  383 abr 11 14:01 values.yaml
```
Content of `values.yaml`
```
➜  testapp-cli cat values.yaml      
epinio:
  appName: testapp
  configpaths: []
  configurations: []
  env: []
  imageURL: 127.0.0.1:30500/apps/workspace-testapp:33b9adf5282b4d56
  ingress: null
  replicaCount: 1
  routes:
  - domain: testapp.192.168.16.3.omg.howdoi.website
    id: testapp.192.168.16.3.omg.howdoi.website
    path: /
  stageID: 33b9adf5282b4d56
  start: null
  tlsIssuer: epinio-ca
  username: admin
```
