### ISSUE TITLE
De-dupe dex client configuration, assign dex secret

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#180]
Dex integration was added by https://github.com/epinio/ui/issues/167. 

This includes the ability to disable dex and also provide a secure dex client key. However this has led two issues

## Helm dex configuration is duplicated
The epinio chart values now contains duplicate sections for `dex` and `epinio-ui: dex` (see below for example)

## Dex client secret
The dex client contains a secret that is used in it's chart template. This same value must also be used in the epinio-ui chart. This is currently duplicated, but should change to use a kube secret anyway

## Example epinio values.yaml
```
global:
  domain: '<snip>'
dex:
  enabled: true
  ui:
    secret: 'dev-secret1'
epinio-ui:
  epinioUI:
    apiSkipSSL: true
  dex:
    enabled: true
    ui:
      secret: "dev-secret1"
```
