### ISSUE TITLE
[UI] Follow capitalization of user variables in the input field names

### ISSUE THREAD

**Issue by thehejik** [epinio/ui#225]
### Current Behavior
Seen in post (dev) epinio-v1.7.1

Currently first letter of the input field name is always capital, like `Appliseningport`, `Myannotationenum` ...
![image](https://user-images.githubusercontent.com/12828077/232807688-c24226f0-3940-4014-9d72-92a08928db1f.png)

But in the used AppChart resource the variables have camelCase format.
```
  settings:
    appListeningPort:
      type: 'integer'
    myAnnotationString:
      type: string
    myAnnotationEnum:
      type: string
      enum:
        - "first"
        - "second"
        - "third"
    myAnnotationInteger:
      type: integer
      minimum: '1024'
      maximum: '2048'
    myAnnotationNumber:
      type: number
      minimum: '1'
      maximum: '2'
    myAnnotationBool:
      type: bool
```

### Expected Behavior

It would be great if the letters in the variable name would be the same as defined in AppChart resource.
