### ISSUE TITLE
Feature Request: Export the application manifest from the manifest API

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#227]
### Is your feature request related to a problem?

The UI should export the application manifest in a YAML format from the new API (ref: https://github.com/epinio/epinio/issues/2224)

The UI should support importing a manifest in the same format

**Comment by richard-cox** [comment]
Currently blocked on https://github.com/epinio/epinio/issues/2224

**Comment by richard-cox** [comment]
This issues covers
- Fetching the new manifest and providing that for the user to download
- Supplying the new manifest when the user creates an application

**Comment by torchiaf** [comment]
Moved to "In Progress" since it's under review by UI team.

**Comment by mmartin24** [comment]
@torchiaf, given than https://github.com/rancher/dashboard/pull/8970 has been merged, is this ready to be tested?
Just asking because our e2e failed on this part and I just noticed we are exporting yaml files now
Thanks

**Comment by mmartin24** [comment]
Tested on latest `epinio-dev` and `Epinio Server Version: v1.9.0-rc2-1-g2240f783`
 
- Checked that manifest download now produces yaml file.
- Automated test for downloading and reuploading folder [sample.app](https://github.com/epinio/epinio/tree/main/assets/sample-app) working
- Manual test trying the same with `Gitlab`. It works only with the UI yaml, but not with the CI one

This is content of `testapp-gitlab-cli.yml` (gitlab app from cli)
```yml
name: testatpp-gitlab-cli
configuration:
  instances: 1
  routes:
  - testatpp-gitlab-cli.172.19.0.3.omg.howdoi.website
  appchart: standard
origin:
  git:
    revision: bb6883114668e9aed4964ed3f60bed3bc623c202
    url: https://gitlab.com/richard-cox/epinio-sample-app
    provider: gitlab
staging:
  builder: paketobuildpacks/builder:full
namespace: workspace
```

When I try to import it this happens:
![image](https://github.com/epinio/ui/assets/37271841/bf69bebc-1766-401b-b1f1-4be8d7000da1)



This is the content of `workspace-testapp-gitlab-ui-2023-06-02T14_47_16.yaml` (gitlab app from UI)
```yml
name: testapp-gitlab-ui
configuration:
  instances: 1
  routes:
  - testapp-gitlab-ui.172.19.0.3.omg.howdoi.website
  appchart: standard
origin:
  git:
    revision: bb6883114668e9aed4964ed3f60bed3bc623c202
    url: https://gitlab.com/richard-cox/epinio-sample-app
    provider: gitlab
    branch: main
staging:
  builder: paketobuildpacks/builder:full
namespace: workspace
```

Comparing contents I see field `branch` present in UI yaml only, and I guess this is why it fails when using a cli yaml.
![image](https://github.com/epinio/ui/assets/37271841/687333b8-fcae-4f2e-af05-9d6964a5c06e)

@torchiaf , @enrichman 
Is this a BE issue or should the UI mimic what currently has the BE and ignore the branch by using only the revision number?
